### ISSUE TITLE
Unbound

### ISSUE THREAD

**Issue by Joly0** [devzwf/pihole-dot-doh#11]
Hey, is it possible to implement unbound into this container or some way to use this container together with an unbound container?

**Comment by devzwf** [comment]
I can look at that.
But PR are always welcome ;)

**Comment by Joly0** [comment]
Yes, i am just testing it a bit more, fixing stuff and make it ready to push. I´ll open up a pr once i am done

**Comment by devzwf** [comment]
completed by #12
