### ISSUE TITLE
got a version warning

### ISSUE THREAD

**Issue by PoepieFloepie** [devzwf/pihole-dot-doh#4]
Preparing new gravity database...2023-06-25T06:56:39Z INF Version 2023.5.1
INF GOOS: linux, GOVersion: go1.19.6, GoArch: amd64
INF Settings: map[config:/config/cloudflared.yml proxy-dns:true proxy-dns-address:127.1.1.1 proxy-dns-port:5153 proxy-dns-upstream:[https://1.1.1.1/dns-query https://1.0.0.1/dns-query]]
INF Adding DNS upstream url=https://1.1.1.1/dns-query
INF Adding DNS upstream url=https://1.0.0.1/dns-query
INF Starting DNS over HTTPS proxy server address=dns://127.1.1.1:5153
INF cloudflared will not automatically update if installed by a package manager.

WRN Your version 2023.5.1 is outdated. We recommend upgrading it to 2023.6.1

i have a synology 220+ dsm 7.2 latest

**Comment by devzwf** [comment]
looking into it....
seems like actions failed

**Comment by devzwf** [comment]
Anb BTW you should be using 2023.5.2

**Comment by devzwf** [comment]
yes working on it ....

**Comment by devzwf** [comment]
New version available with latest cloudflared.
https://hub.docker.com/r/devzwf/pihole-dot-doh
Thanks
