### ISSUE TITLE
update of stubby

### ISSUE THREAD

**Issue by PoepieFloepie** [devzwf/pihole-dot-doh#5]
i see stubby is still on version 0.3.0

what i see on github from stubby is version *2022-12-22: version 0.4.3

https://github.com/getdnsapi/stubby/blob/develop/ChangeLog

or do i look at the wrong github,and there are newer versions

or is the 0.3.0 version better then the newer ones

if not is it possible to update it..

**Comment by devzwf** [comment]
I am installing Stubby, as part of of os package manager  , ie `apt install stubby`
so i install what debian bullseye provide.

**Comment by PoepieFloepie** [comment]
oke thanks for the fast replay .

and sorry for the stupid quistion...
you know more about this then me

but thanks for the info....

**Comment by devzwf** [comment]
there is no stupid question....
all of them were valid
thanks
