### ISSUE TITLE
one dns default and the other as fallback

### ISSUE THREAD

**Issue by PoepieFloepie** [devzwf/pihole-dot-doh#6]
i know this is not a issues..

maybe you know how ,i looked all over the internet but found nothing

so i have 127.2.2.2#5253 as custom 1 ,and i want this one to be default
the fallback would be custom 2 127.1.1.1#5153

i tryed somethings and it always going to the 127.1.1.1#5153

is there a way to do this ,i read somewhere about strict order,but nothing found how to

so sorry to bother you with this.....

**Comment by devzwf** [comment]
In fact i dont think DNS have strict order.....  there is no primary / secondary as we may define it.
it take the one who answer first.

**Comment by PoepieFloepie** [comment]
oke thanks

do you know what this is -if i see the log from pihole in dozzle the i see this line a couple of times
Could not get qname from query: A helper function for dicts had a name argument that for a name that is not in the dict.

**Comment by devzwf** [comment]
Look like a stubby issue... 
But that all i can say sadly

**Comment by devzwf** [comment]
closing
