### ISSUE TITLE
Port 10443:443, is it for pi-hole https admin web-ui access?

### ISSUE THREAD

**Issue by maxdd** [devzwf/pihole-dot-doh#8]
Hello,
first of all thank you for sharing this ready-to-use docker.
I have a question, while i can access the web-ui from the following url http://my-ip:82/admin i cannot reach it using https://my-ip:10443/admin.

I thought the 10443:443 had the goal to forward the 10443 to the internal 443 which i was hoping for it to be the secure version of the web-ui

Am i missing something?

**Comment by devzwf** [comment]
this should be fixed in the Doc....
i do not expose 443
